#!/bin/bash
runner=$1
extra=$2
fail=0
if [[ "$runner" != "" ]];
then
    echo "Using runner = $runner with extra arguments = $extra"
fi

LOG=$(mktemp)
fail_list=""

for f in \
    core/core.py \
    core/tensors.py \
    core/gamma.py \
    core/block.py \
    core/scalar.py \
    core/checksums.py \
    core/importexport.py \
    core/orthogonalize.py \
    core/matrix.py \
    core/split.py \
    core/other_reps.py \
    random/random-simple.py \
    qcd/a2a.py \
    qcd/fermion-operators.py \
    algorithms/implicitly-restarted-lanczos.py \
    algorithms/solvers.py
do

printf "%-60s" " [TEST] $f"

start=$SECONDS
${runner} $f ${extra} 2>&1 > ${LOG}
res=$?
elapsed=$((SECONDS-start))

if [[ "$res" == "0" ]];
then
    echo "OK  ($elapsed s)"
else
    echo "ERR ($elapsed s)"
    cat ${LOG}
    fail=$((fail+1))
    fail_list="$fail_list $f"
fi

done

if [ -f ${LOG} ];
then
    rm -f ${LOG}
fi

if ((fail != 0))
then
    echo "$fail tests failed:"
    for f in ${fail_list}
    do
	echo $f
    done
    exit 1
else
    echo "All tests successful"
fi
