// This file is automatically generated, do not modify!
INSTANTIATE(vComplexF,single,0)
INSTANTIATE(vComplexF,single,1)
INSTANTIATE(vComplexF,single,2)
INSTANTIATE(vComplexD,double,0)
INSTANTIATE(vComplexD,double,1)
INSTANTIATE(vComplexD,double,2)
